# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1FiiBv5H59fBEj1lufjW4XF-OO8yiN-
"""

import sqlite3
import matplotlib.pyplot as plt
from datetime import datetime


# Database setup
def setup_database():
    conn = sqlite3.connect('workouts.db')
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS workouts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT NOT NULL,
            exercise TEXT NOT NULL,
            sets INTEGER NOT NULL,
            reps INTEGER NOT NULL,
            weight REAL NOT NULL
        )
    ''')
    conn.commit()
    conn.close()

# Add a workout
def add_workout():
    date = input("Enter the date (YYYY-MM-DD): ")
    exercise = input("Enter the exercise name: ")
    sets = int(input("Enter the number of sets: "))
    reps = int(input("Enter the number of reps: "))
    weight = float(input("Enter the weight (in kg/lbs): "))

    conn = sqlite3.connect('workouts.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO workouts (date, exercise, sets, reps, weight)
        VALUES (?, ?, ?, ?, ?)
    ''', (date, exercise, sets, reps, weight))
    conn.commit()
    conn.close()
    print("Workout added successfully!")

# View workout history
def view_history():
    conn = sqlite3.connect('workouts.db')
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM workouts')
    rows = cursor.fetchall()
    conn.close()

    if not rows:
        print("No workout history found.")
        return

    print("\nWorkout History:")
    for row in rows:
        print(f"ID: {row[0]}, Date: {row[1]}, Exercise: {row[2]}, Sets: {row[3]}, Reps: {row[4]}, Weight: {row[5]}")

# Generate progress report
def generate_report():
    exercise = input("Enter the exercise name to generate a report: ")
    conn = sqlite3.connect('workouts.db')
    cursor = conn.cursor()
    cursor.execute('''
        SELECT date, weight FROM workouts WHERE exercise = ? ORDER BY date
    ''', (exercise,))
    data = cursor.fetchall()
    conn.close()

    if not data:
        print(f"No data found for exercise: {exercise}")
        return

    dates = [row[0] for row in data]
    weights = [row[1] for row in data]

    plt.plot(dates, weights, marker='o')
    plt.xlabel('Date')
    plt.ylabel('Weight Lifted')
    plt.title(f'Progress for {exercise}')
    plt.grid(True)
    plt.show()

# Main menu
def main_menu():
    while True:
        print("\nWorkout Progress Tracker")
        print("1. Add Workout")
        print("2. View Workout History")
        print("3. Generate Progress Report")
        print("4. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            try:
                add_workout()
            except ValueError:
                print("Invalid input! Please enter numeric values for sets, reps, and weight.")
        elif choice == '2':
            view_history()
        elif choice == '3':
            generate_report()
        elif choice == '4':
            print("Exiting the application. Goodbye!")
            break
        else:
            print("Invalid choice! Please try again.")

# Entry point
if __name__ == "__main__":
    setup_database()
    main_menu()