# -*- coding: utf-8 -*-
"""simple console timer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhNbFpdU5OEoUOeBWFenL81sLnZC91eJ
"""

import time
my_time = int(input("Enter the time in seconds: "))
if(my_time < 0):
   print("time cannot be less than 0, please enter valid time")

for x in range(my_time,0,-1):
   sec= x % 60
   min= int(x / 60) % 60
   hr= int (x / 3600)
   print(f"{hr:02}:{min:02}:{sec:02}")
   time.sleep(1)
   print("time is up !!!!!")